version: '3.4'

services:
  sql-data-test:
    image: mcr.microsoft.com/mssql/server:2019-latest 

  nosql-data-test:
    image: mongo


  rabbitmq-test:
    image: rabbitmq:3-management-alpine

  identity-api-test:
    image: ${REGISTRY:-eshop}/identity-api-test:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Identity/IdentityAPI/Dockerfile
    depends_on:
      - sql-data-test


  servicelist-api-functional-test:
    image: ${REGISTRY:-the-room}/servicelist-api-functional-test:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/ServiceList/ServiceListAPI/Dockerfile
      target: functionaltest
    depends_on:
      - sql-data-test
      - rabbitmq-test
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests

  servicelist-api-unit-test:
    image: ${REGISTRY:-the-room}/servicelist-api-unit-test:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/ServiceList/ServiceListAPI/Dockerfile
      target: unittest
    depends_on:
      - sql-data-test
      - rabbitmq-test
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests
