version: '3.4'

services:
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "6340:80"

  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "6433:1433"
    volumes:
      - the-room-sqldata:/var/opt/mssql

  nosqldata:
    ports:
      - "28017:28017"
    volumes:
      - the-room-nosqldata:/data/db

  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=the_room
      - RABBITMQ_DEFAULT_PASS=Pass@word
    ports:
      - "16672:15672"
      - "6672:5672"
  
  simple-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SpaClient=http://${THE_ROOM_EXTERNAL_DNS_NAME_OR_IP}:6304
      - ConnectionString=${THE_ROOM_AZURE_IDENTITY_DB:-Server=sqldata;Database=TheRoom.Service.SimpleDb;User Id=sa;Password=Pass@word}
    ports:
      - "6305:80"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SpaClient=http://${THE_ROOM_EXTERNAL_DNS_NAME_OR_IP}:6104
      - ConnectionString=${THE_ROOM_AZURE_IDENTITY_DB:-Server=sqldata;Database=TheRoom.Service.IdentityDb;User Id=sa;Password=Pass@word}
      - BonusApiClient=http://${THE_ROOM_EXTERNAL_DNS_NAME_OR_IP}:5102
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "6105:80"

  service-list-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SpaClient=http://${THE_ROOM_EXTERNAL_DNS_NAME_OR_IP}:8106
      - ServiceListClient=http://${THE_ROOM_EXTERNAL_DNS_NAME_OR_IP}:7105
      - BonusAPIClient=http://${THE_ROOM_EXTERNAL_DNS_NAME_OR_IP}:6105
      - ConnectionString=${THE_ROOM_AZURE_SERVICE_LIST_DB:-Server=sqldata;Database=TheRoom.Service.ServiceListDb;User Id=sa;Password=Pass@word}
      - EventBusRetryCount=5
      - EventBusUserName=${THE_ROOM_SERVICE_BUS_USERNAME}
      - EventBusPassword=${THE_ROOM_SERVICE_BUS_PASSWORD}
      - EventBusConnection=${THE_ROOM_AZURE_SERVICE_BUS:-rabbitmq}
      - GRPC_PORT=81
      - PORT=80
      - IdentityUrlExternal=http://localhost:6105
      - IdentityUrl=http://localhost:6105
      - UseCustomizationData=True
      - AzureServiceBusEnabled=False
      - AzureStorageEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "7105:80"

  the-room-react-app:
    environment:
      - REACT_APP_SERVICE_LIST_SERVICE=http://localhost:7105
      - REACT_APP_IDENTITY_URL=http://localhost:6105
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "8106:3000"

  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecksUI__HealthChecks__0__Name=The Simple API Check
      - HealthChecksUI__HealthChecks__0__Uri=http://simple-api/hc
      - HealthChecksUI__HealthChecks__1__Name=Identity HTTP Check
      - HealthChecksUI__HealthChecks__1__Uri=http://identity-api/hc
      - HealthChecksUI__HealthChecks__2__Name=Service List API Check
      - HealthChecksUI__HealthChecks__2__Uri=http://service-list-api/hc
      - HealthChecksUI__HealthChecks__3__Name=The Room React APP
      - HealthChecksUI__HealthChecks__3__Uri=http://the-room-react-app/hc
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "6107:80"

volumes:
  the-room-sqldata:
    external: false
  the-room-nosqldata:
    external: false