version: '3.4'

services:
  seq:
    image: datalust/seq:latest

  sql-data:
    image: mcr.microsoft.com/mssql/server:2019-latest

  nosqldata:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  simple-api:
    image: ${REGISTRY:-the-room}/simple-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Simple/TheRoomSimpleAPI/Dockerfile
    depends_on:
      - sql-data

  identity-api:
    image: ${REGISTRY:-the-room}/identity-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Identity/IdentityAPI/Dockerfile
    depends_on:
      - sql-data
  
  service-list-api:
    image: ${REGISTRY:-the-room}/service-list-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/ServiceList/ServiceListAPI/Dockerfile
    depends_on:
      - identity-api
      - sql-data
      - rabbitmq

  bonus-api:
    image: ${REGISTRY:-the-room}/bonus-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Bonus/BonusAPI/Dockerfile
    depends_on:
      - identity-api
      - sql-data
  
  the-room-react-app:
    image: ${REGISTRY:-the-room}/react-app:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Web/the-room/Dockerfile
    depends_on:
      - identity-api

  webstatus:
    image: ${REGISTRY:-the-room}/webstatus:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Web/WebStatus/Dockerfile